services:
  db:
    image: postgres:17-alpine
    container_name: uptime_monitor-db
    restart: on-failure:3
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - uptime_monitor-network
    deploy:
      resources:
        limits:
          cpus: "1"
        reservations:
          cpus: "0.25"

  redis:
    image: redis:8.0.3-alpine
    container_name: uptime_monitor-redis
    restart: on-failure:3
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - uptime_monitor-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: ".75"
        reservations:
          memory: 256M
          cpus: "0.25"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: uptime_monitor-backend
    restart: on-failure:5
    environment:
      APP_ENV: dev
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - uptime_monitor-network
    deploy:
      resources:
        limits:
          cpus: "2"
        reservations:
          cpus: "0.5"

networks:
  uptime_monitor-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
